export const SAMPLE_TOPIC_NAMES = [
  "Beneficiary Engagement",
  "PHE-COVID-19",
  "Aggregate Cap",
  "Annual Limits",
  "Basic Health Plan (BHP)",
  "Behavioral Health",
  "Children's Health Insurance Program (CHIP)",
  "CMMI - AHEAD",
  "CMMI - Integrated Care for Kids (IncK)",
  "CMMI - Maternal Opioid Misuse (MOM)",
  "Community Engagement",
  "Contingency Management",
  "Continuous Eligibility",
  "Delivery System Reform Incentive Payment (DSRIP)",
  "Dental",
  "Designated State Health Programs (DSHP)",
  "Employment Supports",
  "Enrollment Cap",
  "End-Stage Renal Disease (ESRD)",
  "Expenditure Cap",
  "Former Foster Care Youth (FFCY)",
  "Global Payment Program (GPP)",
  "Health Equity",
  "Health-Related Social Needs (HRSN)",
  "Healthy Behavior Incentives",
  "HIV",
  "Home Community Based Services (HCBS)",
  "Lead Exposure",
  "Lifetime Limits",
  "Long-Term Services and Supports (LTSS)",
  "Managed Care",
  "Marketplace Coverage/Premium Assistance Wrap",
  "New Adult Group Expansion",
  "Non-Eligibility Period",
  "Non-Emergency Medical Transportation (NEMT)",
  "Partial Expansion of the New Adult Group",
  "Pharmacy",
  "PHE-Appendix K",
  "PHE-Reasonable Opportunity Period (ROP)",
  "PHE-Risk Mitigation",
  "PHE-Vaccine Coverage",
  "Premiums/Cost-Sharing",
  "Provider Cap",
  "Provider Restriction",
  "ReEntry",
  "Reproductive Health: Family Planning",
  "Reproductive Health: Fertility",
  "Reproductive Health: Hyde",
  "Reproductive Health: Maternal Health",
  "Reproductive Health: Post-Partum Extension",
  "Reproductive Health: RAD",
  "Retroactive Eligibility",
  "Serious Mental Illness (SMI)",
  "Special Needs",
  "Substance Use Disorder (SUD)",
  "Targeted Population Expansion",
  "Tribal",
  "Uncompensated Care",
  "Value Based Care (VBC)",
  "Vision",
];
