repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: no-commit-to-branch
      - id: check-case-conflict

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: 'data-migration/reports/prisma_ddl.manifest.json'

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.6.6
    hooks:
    - id: pydoclint
      args: ["--config=data/migration/pyproject.toml"]
