"""Tests for ``docs/tools/table_flow_to_adoc.py`` (offline, no DB).

Covers:

* Drift guard: a fresh render of each partial equals the committed file under
  ``docs/shared/generated/`` (so editing ``reports/`` or ``sql/`` without
  rerunning ``make flow-pages`` fails CI).
* Anchor strings in the rendered partials.
* ``main`` writes all three partials and returns 0.
* Fail-closed lints (exit 1) for: a target table with no column-map rows, a
  missing crosswalk CSV, and a missing stage SQL path.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
TOOL_PATH = REPO_ROOT / "docs" / "tools" / "table_flow_to_adoc.py"
GENERATED_DIR = REPO_ROOT / "docs" / "shared" / "generated"


def _load_module():
    spec = importlib.util.spec_from_file_location("table_flow_to_adoc", TOOL_PATH)
    assert spec is not None
    assert spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


MOD = _load_module()
CFG = MOD.CONFIGS["demonstration"]
CFG_AMENDMENT = MOD.CONFIGS["amendment"]


def test_render_columns_matches_committed() -> None:
    committed = (GENERATED_DIR / "demonstration-flow-columns.adoc").read_text(encoding="utf-8")
    assert MOD.render_columns(CFG) == committed, "rerun `make flow-pages` and commit"


def test_render_crosswalks_matches_committed() -> None:
    committed = (GENERATED_DIR / "demonstration-flow-crosswalks.adoc").read_text(encoding="utf-8")
    assert MOD.render_crosswalks(CFG) == committed, "rerun `make flow-pages` and commit"


def test_render_stages_matches_committed() -> None:
    committed = (GENERATED_DIR / "demonstration-flow-stages.adoc").read_text(encoding="utf-8")
    assert MOD.render_stages(CFG) == committed, "rerun `make flow-pages` and commit"


def test_amendment_render_columns_matches_committed() -> None:
    committed = (GENERATED_DIR / "amendment-flow-columns.adoc").read_text(encoding="utf-8")
    assert MOD.render_columns(CFG_AMENDMENT) == committed, "rerun `make flow-pages` and commit"


def test_amendment_render_crosswalks_matches_committed() -> None:
    committed = (GENERATED_DIR / "amendment-flow-crosswalks.adoc").read_text(encoding="utf-8")
    assert MOD.render_crosswalks(CFG_AMENDMENT) == committed, "rerun `make flow-pages` and commit"


def test_amendment_render_stages_matches_committed() -> None:
    committed = (GENERATED_DIR / "amendment-flow-stages.adoc").read_text(encoding="utf-8")
    assert MOD.render_stages(CFG_AMENDMENT) == committed, "rerun `make flow-pages` and commit"


def test_amendment_columns_anchor_strings() -> None:
    body = MOD.render_columns(CFG_AMENDMENT)
    assert "`demos_app.amendment`" in body
    assert "`mysql_raw.mdcd_demo_amndmt`" in body
    assert "crosswalk:amendment_status" in body


def test_amendment_stages_are_numbered_and_existence_checked() -> None:
    body = MOD.render_stages(CFG_AMENDMENT)
    assert "| 1 | `sql/10_stg/13_filter_amndmt.sql`" in body
    assert "sql/20_app/35_amendment.sql" in body
    assert "sql/99_parity/52_amendment_load.sql" in body


def test_columns_anchor_strings() -> None:
    body = MOD.render_columns(CFG)
    assert "`demos_app.demonstration`" in body
    assert "`mysql_raw.mdcd_demo`" in body
    assert "crosswalk:demo_status" in body
    assert "`id_map`" in body


def test_crosswalks_render_null_sentinel() -> None:
    body = MOD.render_crosswalks(CFG)
    # sdg_division legacy sentinel 0 has an empty demos_text_id -> rendered NULL.
    assert "(NULL)" in body
    assert "Withdrawn" in body  # demo_status code 9


def test_stages_are_numbered_and_existence_checked() -> None:
    body = MOD.render_stages(CFG)
    assert "| 1 | `sql/10_stg/10_filter_demo.sql`" in body
    assert "sql/20_app/30_demonstration.sql" in body
    assert "sql/99_parity/11_demonstration_completeness.sql" in body


def test_main_writes_all_three(tmp_path: Path) -> None:
    rc = MOD.main(["--table", "demonstration", "--out-dir", str(tmp_path)])
    assert rc == 0
    for name in (
        "demonstration-flow-columns.adoc",
        "demonstration-flow-crosswalks.adoc",
        "demonstration-flow-stages.adoc",
    ):
        body = (tmp_path / name).read_text(encoding="utf-8")
        assert body.startswith("// Generated by docs/tools/table_flow_to_adoc.py")


def test_lint_missing_target_rows_exits() -> None:
    bad = MOD.TableFlowConfig(
        table="demonstration",
        target_table="no_such_demos_table",
        source_anchor="mdcd_demo",
        crosswalks=[],
        stages=[],
    )
    with pytest.raises(SystemExit) as exc:
        MOD.render_columns(bad)
    assert exc.value.code == 1


def test_lint_missing_crosswalk_csv_exits() -> None:
    bad = MOD.TableFlowConfig(
        table="demonstration",
        target_table="demonstration",
        source_anchor="mdcd_demo",
        crosswalks=[("does not exist", "does_not_exist")],
        stages=[],
    )
    with pytest.raises(SystemExit) as exc:
        MOD.render_crosswalks(bad)
    assert exc.value.code == 1


def test_lint_missing_stage_sql_exits() -> None:
    bad = MOD.TableFlowConfig(
        table="demonstration",
        target_table="demonstration",
        source_anchor="mdcd_demo",
        crosswalks=[],
        stages=[("sql/does/not/exist.sql", "bogus")],
    )
    with pytest.raises(SystemExit) as exc:
        MOD.render_stages(bad)
    assert exc.value.code == 1


def test_esc_escapes_pipes() -> None:
    assert MOD._esc("a|b") == "a\\|b"
    assert MOD._esc("") == ""
