import { EventTypeId } from "demos-server";

export const ALL_EVENT_TYPE_IDS: EventTypeId[] = [
  "LOGIN_SUCCEEDED",
  "LOGOUT_SUCCEEDED",
  "CREATE_DEMONSTRATION_SUCCEEDED",
  "CREATE_DEMONSTRATION_FAILED",
  "CREATE_EXTENSION_SUCCEEDED",
  "CREATE_EXTENSION_FAILED",
  "CREATE_AMENDMENT_SUCCEEDED",
  "CREATE_AMENDMENT_FAILED",
  "EDIT_DEMONSTRATION_SUCCEEDED",
  "EDIT_DEMONSTRATION_FAILED",
  "DELETE_DEMONSTRATION_SUCCEEDED",
  "DELETE_DEMONSTRATION_FAILED",
  "DELETE_DOCUMENT_SUCCEEDED",
  "DELETE_DOCUMENT_FAILED",
];
