FROM mcr.microsoft.com/devcontainers/javascript-node:24-bookworm

RUN apt-get update && \
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get -y install python3 python3-pip python-is-python3 awscli chromium
