insert into permission (id, grant_level_id) values 
  -- entity-level permissions
  ('Access Application Documents', 'System'),
  ('Access Application Workflow', 'System'),
  ('Access Comment Author', 'System'),
  ('Access Comment Deliverable', 'System'),
  ('Access Contact Demonstration', 'System'),
  ('Access Contact Person', 'System'),
  ('Access Deliverable Actions', 'System'),
  ('Access Deliverable CmsDocuments', 'System'),
  ('Access Deliverable PrivateComments', 'System'),
  ('Access Demonstration Contacts', 'System'),
  ('Access Demonstration Deliverables', 'System'),
  ('Access Demonstration DemonstrationTypes', 'System'),
  ('Access Demonstration Modifications', 'System'),
  ('Access Document Application', 'System'),
  ('Access Document Deliverable', 'System'),
  ('Access Document Download', 'System'),
  ('Access Document Owner', 'System'),
  ('Access Document Upload', 'System'),
  ('Access Modification Demonstration', 'System'),
  ('Access Person Contacts', 'System'),
  ('Access State Demonstrations', 'System'),
  ('Access User Deliverables', 'System'),
  ('Access User Documents', 'System'),

  -- action-level permissions
  ('Create Deliverable', 'System'),
  ('Create Demonstration', 'System'),
  ('Create Modification', 'System'),
  ('Delete Deliverable', 'System'),
  ('Delete Demonstration', 'System'),
  ('Delete Document', 'System'),
  ('Delete Modification', 'System'),
  ('Manage Deliverable', 'System'),
  ('Manage Demonstration', 'System'),
  ('Manage Demonstration Contacts', 'System'),
  ('Manage Document', 'System'),
  ('Review Deliverable', 'System'),
  ('Submit Deliverable', 'System'),
  ('Manage Modification', 'System'),
  ('Upload Application Document', 'System'),
  ('Upload Application Workflow Document', 'System'),
  ('Upload Deliverable Document', 'System')
;


INSERT INTO "role_permission" 
VALUES 
  ('Admin User', 'System', 'Access Application Documents'),
  ('Admin User', 'System', 'Access Application Workflow'),
  ('Admin User', 'System', 'Access Comment Author'),
  ('Admin User', 'System', 'Access Comment Deliverable'),
  ('Admin User', 'System', 'Access Contact Demonstration'),
  ('Admin User', 'System', 'Access Contact Person'),
  ('Admin User', 'System', 'Access Deliverable Actions'),
  ('Admin User', 'System', 'Access Deliverable CmsDocuments'),
  ('Admin User', 'System', 'Access Deliverable PrivateComments'),
  ('Admin User', 'System', 'Access Demonstration Contacts'),
  ('Admin User', 'System', 'Access Demonstration Deliverables'),
  ('Admin User', 'System', 'Access Demonstration DemonstrationTypes'),
  ('Admin User', 'System', 'Access Demonstration Modifications'),
  ('Admin User', 'System', 'Access Document Application'),
  ('Admin User', 'System', 'Access Document Deliverable'),
  ('Admin User', 'System', 'Access Document Download'),
  ('Admin User', 'System', 'Access Document Owner'),
  ('Admin User', 'System', 'Access Document Upload'),
  ('Admin User', 'System', 'Access Modification Demonstration'),
  ('Admin User', 'System', 'Access Person Contacts'),
  ('Admin User', 'System', 'Access State Demonstrations'),
  ('Admin User', 'System', 'Access User Deliverables'),
  ('Admin User', 'System', 'Access User Documents'),
  ('Admin User', 'System', 'Create Deliverable'),
  ('Admin User', 'System', 'Create Demonstration'),
  ('Admin User', 'System', 'Create Modification'),
  ('Admin User', 'System', 'Delete Deliverable'),
  ('Admin User', 'System', 'Delete Demonstration'),
  ('Admin User', 'System', 'Delete Document'),
  ('Admin User', 'System', 'Delete Modification'),
  ('Admin User', 'System', 'Manage Deliverable'),
  ('Admin User', 'System', 'Manage Demonstration'),
  ('Admin User', 'System', 'Manage Demonstration Contacts'),
  ('Admin User', 'System', 'Manage Document'),
  ('Admin User', 'System', 'Review Deliverable'),
  ('Admin User', 'System', 'Submit Deliverable'),
  ('Admin User', 'System', 'Manage Modification'),
  ('Admin User', 'System', 'Upload Application Document'),
  ('Admin User', 'System', 'Upload Application Workflow Document'),
  ('Admin User', 'System', 'Upload Deliverable Document'),

  ('CMS User', 'System', 'Access Application Documents'),
  ('CMS User', 'System', 'Access Application Workflow'),
  ('CMS User', 'System', 'Access Comment Author'),
  ('CMS User', 'System', 'Access Comment Deliverable'),
  ('CMS User', 'System', 'Access Contact Demonstration'),
  ('CMS User', 'System', 'Access Contact Person'),
  ('CMS User', 'System', 'Access Deliverable Actions'),
  ('CMS User', 'System', 'Access Deliverable CmsDocuments'),
  ('CMS User', 'System', 'Access Deliverable PrivateComments'),
  ('CMS User', 'System', 'Access Demonstration Contacts'),
  ('CMS User', 'System', 'Access Demonstration Deliverables'),
  ('CMS User', 'System', 'Access Demonstration DemonstrationTypes'),
  ('CMS User', 'System', 'Access Demonstration Modifications'),
  ('CMS User', 'System', 'Access Document Application'),
  ('CMS User', 'System', 'Access Document Deliverable'),
  ('CMS User', 'System', 'Access Document Download'),
  ('CMS User', 'System', 'Access Document Owner'),
  ('CMS User', 'System', 'Access Document Upload'),
  ('CMS User', 'System', 'Access Modification Demonstration'),
  ('CMS User', 'System', 'Access Person Contacts'),
  ('CMS User', 'System', 'Access State Demonstrations'),
  ('CMS User', 'System', 'Access User Deliverables'),
  ('CMS User', 'System', 'Access User Documents'),
  ('CMS User', 'System', 'Create Deliverable'),
  ('CMS User', 'System', 'Create Demonstration'),
  ('CMS User', 'System', 'Create Modification'),
  ('CMS User', 'System', 'Delete Deliverable'),
  ('CMS User', 'System', 'Delete Demonstration'),
  ('CMS User', 'System', 'Delete Document'),
  ('CMS User', 'System', 'Delete Modification'),
  ('CMS User', 'System', 'Manage Deliverable'),
  ('CMS User', 'System', 'Manage Demonstration'),
  ('CMS User', 'System', 'Manage Demonstration Contacts'),
  ('CMS User', 'System', 'Manage Document'),
  ('CMS User', 'System', 'Review Deliverable'),
  ('CMS User', 'System', 'Submit Deliverable'),
  ('CMS User', 'System', 'Manage Modification'),
  ('CMS User', 'System', 'Upload Application Document'),
  ('CMS User', 'System', 'Upload Application Workflow Document'),
  ('CMS User', 'System', 'Upload Deliverable Document'),

  ('State User', 'System', 'Access Comment Author'),
  ('State User', 'System', 'Access Comment Deliverable'),
  ('State User', 'System', 'Access Contact Demonstration'),
  ('State User', 'System', 'Access Contact Person'),
  ('State User', 'System', 'Access Deliverable Actions'),
  ('State User', 'System', 'Access Deliverable CmsDocuments'),
  ('State User', 'System', 'Access Demonstration Deliverables'),
  ('State User', 'System', 'Access Demonstration DemonstrationTypes'),
  ('State User', 'System', 'Access Document Deliverable'),
  ('State User', 'System', 'Access Document Download'),
  ('State User', 'System', 'Access Document Owner'),
  ('State User', 'System', 'Access Document Upload'),
  ('State User', 'System', 'Access Person Contacts'),
  ('State User', 'System', 'Access User Deliverables'),
  ('State User', 'System', 'Access User Documents'),
  ('State User', 'System', 'Submit Deliverable'),
  ('State User', 'System', 'Upload Deliverable Document')
;