import { gql } from "graphql-tag";
import { EventType } from "./eventTypeSchema";
import { Role } from "../role/roleSchema";
import { User } from "../user/userSchema";

export const eventSchema = gql`
  """
  Event represents a user action or system event, mirroring DB structure
  """
  type Event {
    id: ID!          # From B/E (generated by Prisma)
    userId: ID!      # From B/E
    eventTypeId: ID! # From F/E
    withRoleId: ID!  # From B/E
    route: String!   # From F/E
    createdAt: DateTime! # From B/E (generated by Prisma)
    eventData: JSONObject # From F/E
  }

  # An event with all the fields populated for easier querying
  type EventHydrated {
    id: ID!
    user: User!
    eventType: EventType!
    withRole: Role!
    route: String!
    createdAt: DateTime!
    eventData: JSONObject
  }

  type Query {
    events: [EventHydrated!]!
    event(id: ID!): EventHydrated
    eventsByType(eventTypeId: ID!): [EventHydrated!]!
    eventsByUser(userId: ID!): [EventHydrated!]!
    eventsByRoute(route: String!): [EventHydrated!]!
  }
  
  type Mutation {
    logEvent(input: LogEventInput!): EventHydrated!
  }

  """
  Some event inputs come from the client and others will
  need to be populated by the server for a full event record.
  """
  input LogEventInput {
    eventTypeId: ID!
    route: String!
    eventData: JSONObject
  }
`;

type DateTime = Date;
export interface Event {
  id: string;
  userId: string;
  eventTypeId: string;
  withRoleId: string;
  route: string;
  createdAt: DateTime;
  eventData?: object;
}

export interface EventHydrated {
  id: string;
  user: User;
  eventType: EventType;
  withRole: Role;
  route: string;
  createdAt: DateTime;
  eventData?: object;
}

export interface LogEventInput {
  eventTypeId: string;
  route: string;
  eventData?: object;
}
