import { gql } from "graphql-tag";

export const eventSchema = gql`
  """
  Event represents a user action or system event, mirroring DB structure
  """
  type Event {
    id: ID!               # From B/E (generated by Prisma)
    userId: ID!           # From B/E
    eventTypeId: String!  # From F/E
    withRoleId: ID!       # From B/E
    logLevelId: String!   # From F/E
    route: String!        # From F/E
    createdAt: DateTime!  # From B/E (generated by Prisma)
    eventData: JSONObject # From F/E
  }

  # An event with all the fields populated for easier querying
  type EventHydrated {
    id: ID!
    user: User!
    eventTypeId: String!
    withRole: Role!
    logLevelId: String!
    route: String!
    createdAt: DateTime!
    eventData: JSONObject
  }

  type Query {
    events: [EventHydrated!]!
    event(id: ID!): EventHydrated
    eventsByType(eventTypeId: String!): [EventHydrated!]!
    eventsByUser(userId: ID!): [EventHydrated!]!
    eventsByRoute(route: String!): [EventHydrated!]!
  }
  
  type Mutation {
    createEvent(input: CreateEventInput!): EventHydrated!
  }

  """
  Some event inputs come from the client and others will
  need to be populated by the server for a full event record.
  """
  input CreateEventInput {
    eventTypeId: String!
    logLevelId: String!
    route: String!
    eventData: JSONObject!
  }
`;

type DateTime = Date;
export interface Event {
  id: string;
  userId: string;
  eventTypeId: string;
  withRoleId: string;
  logLevelId: string;
  route: string;
  createdAt: DateTime;
  eventData?: object;
}

export interface CreateEventInput {
  eventTypeId: string;
  logLevelId: string;
  route: string;
  eventData: object;
}
