service: clamav-scan

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  timeout: 30

functions:
  scanFile:
    handler: handler.scanFile

package:
  patterns:
    - clamav/**
    - scan-test/**
    - handler.js
    - scanner.js
